### ISSUE TITLE
Config issue on v6.0.0-rc2

### ISSUE THREAD

**Issue by elcheco** [Kdyby/Redis#106]
I tested today v6.0.0-rc2 and an xception was thrown:

![Screenshot 2021-08-25 at 16 55 05](https://user-images.githubusercontent.com/1447985/130814157-81a54929-9e19-4152-b5d9-5528dcb21ac3.png)

Which corresponds to my config in local.neon:
```
redis:
    host: localhost
    port: 6379
    database: 0
    journal: true
    storage: true
    session:
        database: 1
        native: false
    debugger: true
```

The previous version didn't throw an exception on this, are there any config changes, or is it the bug?
