### ISSUE TITLE
Setting different db

### ISSUE THREAD

**Issue by dakorpar** [Kdyby/Redis#67]
This is my config:
```
redis:
    session: {database: 0, native: off}
    storage: {database: 1}
    journal: {database: 2}
```

Everything works, except that storage is as well saved to database 0 instead of 1?
![screenshot_1](https://cloud.githubusercontent.com/assets/9303856/20216026/63f2cbc6-a818-11e6-9b49-73e2bcfa5fd6.png)
Any info?
