### ISSUE TITLE
Multiple storages configuration

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Redis#9]
Allow to create multiple storages tu utilize more databases, therefore making it easier to flush cache on deploy.

Might work as this

```yml
redis:
    additional:
        translator: 0

services:
   translator: App\Translator(@redis.additional.translator)
```

It would create additional not-autowired instance of RedisClient, and also storage+journal, under service name `@redis.additional.translator` would be the storage ready to be used.

**Comment by forrest79** [comment]
@fprochazka We had impleted this, that our clients shared some sort of connection pool. There was only one connection for the same host and port combination and this connection knew what DB was selected. If client wanted to send some command to Redis, got connection based on host and port from pool and check, if this connection had selected proper database. If not, select DB was made before command. I have made some measurements and creating new connection is about 20x slower, than select command. But you can switch DB many times in one request and that difference can be cleared. I can image some sort of RedisSharedClient, based on RedisClient but with shared drivers. I can prepear pull request, if you want. We have replaced our Redis lib with Kdyby/Redis and canceled this functionality because in 95% requests, we are connection only to one database - so we need only one RedisClient for RedisStorage and RedisJournal. But I will be happy to have possibility to choose which technics is better for me,

**Comment by fprochazka** [comment]
Kdyby/Redis curretly has the ability to configure mupltiple clients 

```yml
	redis:
		journal: on
		storage: on
		session: {native: off}

		clients:
			emailsCount < sessionHandler:
				database: 2

			sentMessages < sessionHandler:
				database: 3

			adminNotifications < sessionHandler:
				database: 4

			doctrine < default:
				database: 6
				debugger: off
```

no client except the default one (that is used in store and journal) is autowired and has to be provided by service name

```yml
	annotations:
		cache: redis(@redis.doctrine_client::getDriver())
```

But I like your idea @forrest79, it could be an optional/alternative client for connecting.
